name: Reagent request
description: Requesting reagents from paper
title: "<Example: Requesting Cas9 expression plasmid>"
labels: ["reagent request"]
assignees:
  - rasi
body:
  - type: markdown
    attributes:
      value: >
        We are happy to share all [plasmids](https://github.com/rasilab/nugent_2024/blob/main/data/supplementary_tables/table_s2_list_of_plasmids.csv) 
        and most [cell lines](https://github.com/rasilab/nugent_2024/blob/main/data/supplementary_tables/table_s4_list_of_celllines.csv) 
        developed as part of this paper. 
        We are unable to ship cell line pools with integrated plasmid libraries 
        since they need large volume culturing to maintain library diversity.
  - type: input
    id: name
    attributes:
      label: Requester name
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: institution
    attributes:
      label: Institution
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email address or a link to your contact info webpage
    validations:
      required: true
  - type: checkboxes
    id: request-type
    attributes:
      label: What are you requesting?
      description: You may select more than one
      options:
        - label: Plasmid(s)
        - label: Cell line(s)
  - type: textarea
    id: reagent-list
    attributes:
      label: Reagents requested
      description: Please provide a list of the reagent(s) that you would like us to send.
      placeholder: |
        example:
        - pHPHS806 (reporter vector)
        - hsPN266 (Cas9 landing pad cell line)
      value: 
    validations:
      required: true  
  - type: dropdown
    id: shipping-method
    attributes:
      label: Shipping method
      description: How would you like to handle shipping arrangements?
      options:
        - Share FedEx account number below
        - Will email shipping details to rasi@fredhutch.org
    validations:
      required: true
  - type: input
    id: shipping-details
    attributes:
      label: Shipping details
      description: |
        Based on your selection above:
        - If sharing publicly: Enter your FedEx account number
        - If emailing privately: Enter "Will send via email" (for FedEx account or alternative shipping arrangements)
      placeholder: e.g., FedEx #123456789 or "Will send via email"
    validations:
      required: true
  - type: textarea
    id: shipping-address
    attributes:
      label: Shipping address
      description: Please provide the address that you would like the reagent(s) sent to.
      placeholder: 
      value: 
    validations:
      required: true
  - type: textarea
    id: anything-else 
    attributes:
      label: Anything else?
      description: Please include here anything else specific to your request.
      placeholder: 
      value: 
    validations:
      required: false
