name: Protocol question
description: Questions related to materials or methods used in the paper
title: "<Example: Enzyme used for PCR amplification during cloning>"
labels: ["protocol"]
assignees:
  - rasi
body:
  - type: markdown
    attributes:
      value: |
        We are happy to address any questions on the materials and methods used in the paper.
  - type: input
    id: name
    attributes:
      label: Requester name
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: institution
    attributes:
      label: Institution
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email address or a link to your contact info webpage
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Questions
      description: What would you like to ask us?
      placeholder: 
      value: 
    validations:
      required: true  
