name: Clarification
description: All other questions about the paper   
title: "<example: Reason for choice of cell line>"
labels: ["question"]
assignees:
  - rasi
body:
  - type: markdown
    attributes:
      value: >
        Please let us know if you would like us to clarify any points from the paper. We will be happy to answer your question.
  - type: input
    id: name
    attributes:
      label: Requester name
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: institution
    attributes:
      label: Institution
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email address or a link to your contact info webpage
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Questions or comments
      description: What would you like us to clarify?
      placeholder: 
      value: 
    validations:
      required: true  
